### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by pmjservey** [Epsilon-Alpha/heupgrade#1]
Its not getting upgrade in my chrome

**Comment by Epsilon-Alpha** [comment]
What issue are you having? Do you have sufficient money?

**Comment by jake285** [comment]
if you use tampermonkey then copy code into a new script then click edit, then find "ENTER ACCOUNT INFO" 
![screenshot 2018-01-18 at 3 41 12 pm](https://user-images.githubusercontent.com/35579181/35120640-c6c213d0-fc66-11e7-9283-baa3458dac08.png)
(i put the X's there but thats what it looks like)
and put your bank account number inbetween the 's

**Comment by pmjservey** [comment]
Jake285 its work now after i put account number. i didn't knew it before!

**Comment by Epsilon-Alpha** [comment]
Glad to know. :)


If I happen to play for a couple of days sometime, I'll make a button click trigger for the upgrade instead of the prompt that appears. 




On Fri, Jan 19, 2018 at 11:34 PM +0530, "pmjservey" <notifications@github.com> wrote:












Jake285 its work now after i put account number. i didn't knew it before!

**Comment by pmjservey** [comment]
is it can't upgrade Ext Hdd?

**Comment by jake285** [comment]
it says it can but i never got it to work, just use the XHD glith, start upload of biggest softs (in GB) to XHD and start other softs upload to XHD, wait for them ALL to finish then click run/complete on all of them and   volla your XHD's GB storage don't matter

**Comment by Jyhade101** [comment]
is there any way to set this up to upgrade ram too? it would seem it would just need maybe 6 lines or so of code but im no good with javascript

**Comment by jake285** [comment]
it upgrades ram automatically

**Comment by Jyhade101** [comment]
every time ive used it it doesnt, thats why i was asking. maybe i have an
old script?

**Comment by jake285** [comment]
idk then, i use the HE upgrade 3.2 and it works just fine

**Comment by Jyhade101** [comment]
Where can I find this, as all I've been able to find is 3.1
