### ISSUE TITLE
Out of money error

### ISSUE THREAD

**Issue by lucacastelnuovo** [Epsilon-Alpha/heupgrade#2]
I have entered my account number without the pound. But when I try to use it I get an `Out of money` error. I am not out of money so this is weird. Also I only have one account.

**Comment by IllumiseGIT** [comment]
Ok

**Comment by lucacastelnuovo** [comment]
Thanks memes

**Comment by lucacastelnuovo** [comment]
Did you create an account to reply t0 me?

**Comment by IllumiseGIT** [comment]
Yeaaa

**Comment by IllumiseGIT** [comment]
32%

**Comment by heeliumxd** [comment]
i only wrote a comment because illumise commented here and it gave me the bright idea of commenting to be in #information channel

**Comment by IllumiseGIT** [comment]
shut up

**Comment by lucacastelnuovo** [comment]
He guys

**Comment by heeliumxd** [comment]
rude

**Comment by IllumiseGIT** [comment]
@everyone

**Comment by IllumiseGIT** [comment]
@Illumise#6501

**Comment by lucacastelnuovo** [comment]
ok so imma close this issue

**Comment by heeliumxd** [comment]
logfro won't like this i think

**Comment by lucacastelnuovo** [comment]
he i wanted to do that

**Comment by IllumiseGIT** [comment]
wait it didn't close

**Comment by heeliumxd** [comment]
good
